# Generated by Django 5.2.7 on 2025-12-13 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_upsated_at_post_updated_at_post_body_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='updated_at',
        ),
    ]
